import Foundation

/// Whether the user framed the entry as a clinical visit note or personal journaling (drives summarization).
public enum SessionEntryIntent: String, Codable, Sendable, Hashable {
    /// Appointment, clinical encounter, or note intended as a medical visit summary.
    case clinicalVisit
    /// Personal reflection or journal the user recorded for themselves.
    case personalJournal
}

/// How the session transcript was captured.
public enum SessionInputType: String, Codable, Sendable {
    case audio
    /// Legacy OCR/scan/photo uploads before PDF/text was distinguished (`documentImage` / `documentFile`).
    case document
    /// VisionKit “scan papers” (multi-page document camera).
    case documentScan
    /// Device camera, photo library, or shared image → OCR text (Photos add path).
    case documentImage
    /// Imported `.pdf` / plain-text file content.
    case documentFile
}

/// A persisted recording session: metadata, full transcript, and optional AI-generated fields.
public struct Session: Codable, Equatable, Hashable, Identifiable, Sendable {
    public let id: UUID
    public var date: Date
    public var transcript: String
    /// Short appointment title generated by the AI summary (e.g. "Back pain follow-up").
    /// `nil` until a summary has been requested for this session.
    public var title: String?
    /// Full medical summary in markdown, generated on demand and cached here.
    /// `nil` until a summary has been requested for this session.
    public var summary: String?
    /// How the transcript was captured. Defaults to `.audio` for legacy sessions.
    public var inputType: SessionInputType
    /// User-selected intent for audio (and audio file) entries; defaults to clinical visit for legacy data.
    public var entryIntent: SessionEntryIntent
    /// Optional folder assignment; `nil` means the entry is only listed under “All entries.”
    public var folderID: UUID?

    enum CodingKeys: String, CodingKey {
        case id, date, transcript, title, summary, inputType, entryIntent, folderID
    }

    public init(
        id: UUID = UUID(),
        date: Date = Date(),
        transcript: String,
        title: String? = nil,
        summary: String? = nil,
        inputType: SessionInputType = .audio,
        entryIntent: SessionEntryIntent = .clinicalVisit,
        folderID: UUID? = nil
    ) {
        self.id = id
        self.date = date
        self.transcript = transcript
        self.title = title
        self.summary = summary
        self.inputType = inputType
        self.entryIntent = entryIntent
        self.folderID = folderID
    }

    // Custom decoder so existing persisted sessions (without inputType) default to .audio.
    public init(from decoder: Decoder) throws {
        let c = try decoder.container(keyedBy: CodingKeys.self)
        id        = try c.decode(UUID.self,   forKey: .id)
        date      = try c.decode(Date.self,   forKey: .date)
        transcript = try c.decode(String.self, forKey: .transcript)
        title     = try c.decodeIfPresent(String.self, forKey: .title)
        summary   = try c.decodeIfPresent(String.self, forKey: .summary)
        inputType = try c.decodeIfPresent(SessionInputType.self, forKey: .inputType) ?? .audio
        entryIntent = try c.decodeIfPresent(SessionEntryIntent.self, forKey: .entryIntent) ?? .clinicalVisit
        folderID = try c.decodeIfPresent(UUID.self, forKey: .folderID)
    }
}
